AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Prefix:
    Type: String
  EnvName:
    Type: String

Conditions:
  IsNotFeatureEnv: !Or [!Equals [!Ref EnvName, production], !Equals [!Ref EnvName, staging], !Equals [!Ref EnvName, develop]]

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-${EnvName}-source
      VersioningConfiguration:
        Status: Enabled

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-${EnvName}-artifact
      VersioningConfiguration:
        Status: Enabled

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvName}-codebuild-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudfront:CreateInvalidation
                  - s3:*
                Resource:
                  - "*"

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvName}-cloudformation-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CloudFormationNestedCFNAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:*
                  - application-autoscaling:*
                  - cloudfront:*
                  - cloudformation:*
                  - dynamodb:*
                  - iam:*
                  - lambda:*
                  - route53:*
                  - route53domains:*
                  - s3:*
                  - ssm:*
                Resource: "*"

  CodePipeLineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvName}-codepipeline-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:*
                  - cloudformation:*
                  - iam:*
                  - s3:*
                Resource: "*"

  TestingEnvironment:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub testing-${EnvName}
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
        Name: source-output
      Source:
        Type: CODEPIPELINE
        BuildSpec: tests/buildspec.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ENV_NAME
            Value: !Ref EnvName
        Image: aws/codebuild/standard:2.0
        Type: LINUX_CONTAINER

  Pipeline:
    DependsOn:
      - ArtifactBucket
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub pipeline-${EnvName}
      RoleArn: !GetAtt CodePipeLineRole.Arn
      ArtifactStore:
          Type: S3
          Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                S3Bucket: !Ref SourceBucket
                S3ObjectKey: source.zip
              OutputArtifacts:
                - Name: source-output
        - Name: !Sub ${EnvName}-environment
          Actions:
            - Name: DeployStorage
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              InputArtifacts:
                - Name: source-output
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                ChangeSetName: DeployStorage
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                StackName: !Sub storage-${EnvName}
                TemplatePath: source-output::storage/template.yml
                TemplateConfiguration: !If [IsNotFeatureEnv, !Sub "source-output::config/${EnvName}.json", "source-output::config/feature.json"]
                RoleArn: !GetAtt CloudFormationRole.Arn
            - Name: Test
              RunOrder: 2
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: source-output
              Configuration:
                ProjectName: !Ref TestingEnvironment
