AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Prefix:
    Type: String
  RepoUrl:
    Type: String
  RepoType:
    Type: String
    AllowedValues:
      - GITHUB
      - BITBUCKET

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Policies:
        - PolicyName: CodeBuildPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - codebuild:*
                  - codepipeline:*
                  - iam:*
                  - logs:*
                  - s3:*
                Resource:
                  - "*"
                  
  Builder:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Prefix}-builder
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Source:
        Auth:
          Type: OAUTH
        Type: !Ref RepoType
        BuildSpec: builder/buildspec.yml
        ReportBuildStatus: true
        Location: !Ref RepoUrl
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/master$
          - - Type: EVENT
              Pattern: PULL_REQUEST_MERGED
            - Type: BASE_REF
              Pattern: ^refs/heads/develop$
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/feature/.*
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/release/.*
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: PREFIX
            Value: !Sub ${Prefix}
        Image: aws/codebuild/standard:2.0
        Type: LINUX_CONTAINER